language: node_js
node_js: 
  - "stable"
services:
  - mongodb
cache:
  directories:
    - "node_modules"
before_script: cd services
branches:
  - intergration
script:
  - npm run test
  - npm run test-backend
  - npm run test-frontend

