language: node_js
node_js:
- stable
services:
- mongodb
cache:
  directories:
  - node_modules
before_script:
- cd services
- npm install
branches:
  only:
  - intergration
  - develop
script:
- npm run test
env:
  global:
  - secure: vJHzZgfIXJzPlVqNlnxuVxr7Vyy+CO7Ct8BadO6DegnMAc06FIOithRBxcML+UEa3+31U50f/ddzU+wZK3jWiC0L4zPSUCAFL+zMmiTWCjkLj4lu/V8tAZdOEri+pCwxQVluDOt+HHK1tumICe/cddpF24b9T/akmCLXDd3bmNyY9qS8eBTZsAklL/tiens5GXFZ+FUmX1tbj/pM4Bks5XNAL/GwWcSnK+o36dv4/l3SGmJKFbMvs/XBBLPF1qHIdpZBiaPK5ov61A4OMIYekgCJ4TFZ2uDiMstMJPrddKWjwPm0a1+aPEa/Bphn8+SNsW08dTBiiSDvCMDy/MnAkenwgmkzv3nBqF8ccfNEkiMyoVdgGC3wV/S4Rmdj9kk27Mg8SzbPqI0GUpRQCxQpb5U4Hg6kfTAbKcbhXZmdM7eD68NDn93PZxkIMyhq8GMjGWudlj/pxMHefD6F3+50E4eOBTGqDxArE1rpJJp1O4KZtBq4IdcM81pgzPdNLMT3wGJTgbTSr9g1zD3eGVxEkRkBaxT+IC41WgosYUW8RhK5YYKp7812g0u6Ds3Ax7UfjVF0nSTDJfwxmNYvsORCKet/nNzmsZmCqIqSwnf/ugnRmleJ/Iwqhxl3Pm5klxWuXALWq+5SwdnkvXI0JI6g5BemN2ReCyNfj6qATRJXAZw=
  - secure: OWv7PT8CyM7VO8VjFX0Og2hXyDsMnzE5qR0jlxvqxINc39+KoswNfVSpCsLhtx258JgLY6Z46DN1nKsJ6TKFBiQgGd/BczncENR0Rn/i72hiycmaOSbpmRxz6Ethk4qjdm6XkWQWEdUKFzSVvzZpLJLPQXRGIh0VRsZuKJg2x2hm81LBAjFqAQCwtSTwoiTb6uESrxNjLWG8EcLH88oGA/FlnLVwsNTAwMKyx3tT3shoHZLQJUp1ZBpxDYoRcLMzvOwIDZqGE0zXn/reIYcXA3yXwDNF5rROakjE3f9QwbF/XxLR+7POxiEVTlIWBAtWMCNrbLxfK8gkLxoRI1QUVXJ5/pd8WxWMzWwP4en7LraHiWmq2TXAfmguziNOwvbFcfcjf+ST1JS0/rZBpyFV50prgVJqSu9rnDZ4uMPbBcelY05MZ3M2cUttifSoTAUh/ucK0+V3oWMPTR3fuxOIxDo93PVXvrT1/D1+K9tLrfOvyE7y3TwfUGpISRSRUaH+j1H3xGjgpuvFDFNlk45eOUVpKmNibHXHsAB5efNNvZFvUGl/WLwyPlyt3GG6NiXtUmL6D4J9I4bp2mRG8+JvB+UUPV2zr9ohiJ9MoYfxO7hQx4kW4BLlpaxE1og8+RwziHcjqKC/3o3k1MyU6sIw62uUjjRZ2Tg/4Ntwa6R0Ups=
  - secure: SgbWt4cP8FhbhIIq2CKIgUDL6Br3KqZt3m1Fqga83AgF3lZSCIIB/EeBqwwWALvCIVd39qMfXFFJHy8H+F8MDoE//s+DcC17Y21GcBg5cYPCVlLFwG74FjC0IFYluox+Cnlob0MsS7kgW1lWaaiOX9X/9gRNRPpvDZGbf6xObjyH51/Vh6Oi2nQN1uQbiuSc9kIvPJ9WVtEovtAFhTUdfUEt6NJQlDj3yy9tvEPT8q+DgnIc7J17ISJMIEinSlHZRFzLmXVORTaAuvw7hTJmdQ3a+pHMjEm2tfr3jihXWVrY1ChjuaNx2uiTwbq6VFeB8FKxn1nqgDLWqQCtPEF9ITb+cqpfpjC1VMUjihBElfh1tF4WWEQ6pSEA6IrZmlpeqVpioFbtub9bnWGqu5ioo9/rW/I4yPBI+ht9hz7c2JeWp4Uhd25wVnh49Us62BJZVoUTjXXzVWDy+k3w3YHfm4wuB7tFrBMWlt4C7zngf9W7ou0cUYw5fk8mGTjalwb0ByZvgSA4ogZ/dPrXE4uyvfPH1ZYpiT/jdi7EdEMktRXwGO4DewDtF9MeksQADb8fboVnskrMrj8yWK3oLfSC6LjCT5Y+PPh39+DhjsFZvLDum8ibJAzbVJ5rEmHQTsW8x8ubcoLq/uqrb7X8xFrvmMsIvngKwTUYCSQi5ZeuV8g=
